dist:
  name: cisco-otelcol
  description: OpenTelemetry Collector with Cisco IOS XE MDT Telemetry Receiver
  output_path: ./build
  version: 0.1.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.138.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.138.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.138.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.138.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.138.0
  - gomod: github.com/jcohoe/otel-grpc-cisco-receiver v0.1.0
    import: github.com/jcohoe/otel-grpc-cisco-receiver/receiver/ciscotelemetryreceiver
    path: ./
